#ifndef GPIODEFINES_H_
#define GPIODEFINES_H_

#define PORT_4D_DEVICE_DETECT_BITSHIFT      0
#define PORT_4D_BUTTON_A_BITSHIFT           1
#define PORT_4D_BUTTON_B_BITSHIFT           2
#define PORT_4D_SWITCH_IP_BITSHIFT          3

#define PORT_32A_SS_EN_CTRL_BITSHIFT        0
#define PORT_32A_OSC_BITSHIFT               1
#define PORT_32A_EN_5VA_BITSHIFT            2
#define PORT_32A_LED_ENUMERATED_BITSHIFT    3
#define PORT_32A_LED_ALIVE_BITSHIFT         4
#define PORT_32A_USB_SEL_1_BITSHIFT         5
#define PORT_32A_USB_SEL_2_BITSHIFT         6
#define PORT_32A_COPRORESET_BITSHIFT        7
#define PORT_32A_ACC_DET_EN_BITSHIFT        8
#define PORT_32A_AUDIO_MUTE_BITSHIFT        9
#define PORT_32A_VBUS_OUT_EN_N_BITSHIFT    10
#define PORT_32A_DAC_RESET_BITSHIFT        28
#define PORT_32A_ADC_RESET_BITSHIFT        29
#define PORT_32A_DSD_MODE_EN_BITSHIFT      30

#define PORTMANAGER_OSC_BITSHIFT            PORT_32A_OSC_BITSHIFT
#define PORTMANAGER_COPRORESET_BITSHIFT     PORT_32A_COPRORESET_BITSHIFT

#endif /*GPIODEFINES_H_*/
